ALTER TABLE `survey_studies` ADD COLUMN IF NOT EXISTS `original_file` VARCHAR(50) NULL DEFAULT NULL;
ALTER TABLE `survey_studies` ADD COLUMN IF NOT EXISTS `google_file_id` VARCHAR(150) NULL DEFAULT NULL;
