ALTER TABLE `survey_users` ADD COLUMN IF NOT EXISTS `first_name` VARCHAR(50) NULL;
ALTER TABLE `survey_users` ADD COLUMN IF NOT EXISTS `last_name` VARCHAR(50) NULL;
ALTER TABLE `survey_users` ADD COLUMN IF NOT EXISTS `affiliation` VARCHAR(350) NULL;
