version: '3'
name: formr
services:
  formr_server:
    container_name: formr_server
#   build: ../.
    image: <$DB_IMAGE>
    ports:
      - 80:80
    networks:
      - default
    volumes:
      - ./settings.php:/var/www/formr.org/config/settings.php
    depends_on:
      - formr_db
      - opencpu
  formr_db:
    container_name: formr_db
    image: <$FORMR_IMAGE>
    networks:
      - default
    restart: always
    environment:
      - MYSQL_DATABASE=formr
      - MYSQL_ROOT_PASSWORD=<$DB_ROOT_PASSWORD>
    volumes:
      - ./db:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/a_schema.sql
      - ./create-formr-user.sql:/docker-entrypoint-initdb.d/b_create-user.sql
  opencpu:
    container_name: opencpu
    #build: ../opencpu
    image: <$OPENCPU_IMAGE>
    networks:
      - default
