version: '3'
name: docker
services:
  formr_server:
    container_name: formr_server
    build: ../.
    ports:
      - 80:80
    networks:
      - default
    volumes:
      - ../docker/settings.php:/var/www/formr.org/config/settings.php
    depends_on:
      - formr_db
      - opencpu
  formr_db:
    container_name: formr_db
    image: mysql:latest
    networks:
      - default
    restart: always
    environment:
      - MYSQL_DATABASE=formr
      - MYSQL_ROOT_PASSWORD=<$DB_ROOT_PASSWORD>
    volumes:
      - ./db:/var/lib/mysql
      - ../sql/schema.sql:/docker-entrypoint-initdb.d/a_schema.sql
      - ./create-formr-user.sql:/docker-entrypoint-initdb.d/b_create-user.sql
  opencpu:
    container_name: opencpu
    build: ../opencpu
    networks:
      - default
